language: node_js
sudo: false
node_js:
  - "0.12"
  - "iojs"

branches:
  only:
    - master

script: "npm run test-ci"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
